const PRODUCTS = [
  {id:1,name:"Add on Aren",variant:"-",category:"Add on",price:0,description:"Tambahan sirup gula aren murni, memberikan rasa manis karamel alami khas Indonesia",image:"images/addon.png"},
  {id:2,name:"Add on Simple Syrup",variant:"-",category:"Add on",price:0,description:"Tambahan sirup gula sederhana (air dan gula) sebagai pemanis dasar untuk semua minuman",image:"images/addon.png"},
  {id:3,name:"Air Mineral",variant:"-",category:"Other",price:5000,description:"Air minum murni dalam kemasan",image:"images/others.png"},
  {id:4,name:"Americano",variant:"Hot Houseblend",category:"Coffee",price:20000,description:"Minuman kopi hitam yang dibuat dengan menambahkan air panas ke shot espresso, menggunakan pilihan biji Houseblend",image:"images/blackhot.png"},
  {id:5,name:"Americano",variant:"Ice Houesblend",category:"Coffee",price:20000,description:"Minuman kopi hitam yang dibuat dengan menambahkan air dingin dan es batu ke shot espresso, menggunakan pilihan biji Houseblend",image:"images/blackice.png"},
  {id:6,name:"Americano",variant:"Hot Arabica",category:"Coffee",price:20000,description:"Minuman kopi hitam yang dibuat dengan menambahkan air panas ke shot espresso, menggunakan pilihan biji Arabica 100%",image:"images/blackhot.png"},
  {id:7,name:"Americano",variant:"Ice Arabica",category:"Coffee",price:20000,description:"Minuman kopi hitam yang dibuat dengan menambahkan air dingin dan es batu ke shot espresso, menggunakan pilihan biji Arabica 100%",image:"images/blackice.png"},
  {id:8,name:"Apple Pie Latte",variant:"-",category:"Coffee",price:24000,description:"Minuman latte dengan perpaduan espresso, susu, dan sirup rasa apel pie yang manis",image:"images/latteice.png"},
  {id:9,name:"Apple Pie Latte (Gedhe)",variant:"-",category:"Menu Gedhe",price:30000,description:"Minuman ukuran besar dari latte dengan perpaduan espresso, susu, dan sirup rasa apel pie yang manis",image:"images/gedhe.png"},
  {id:10,name:"BLACK",variant:"-",category:"Menu Gedhe",price:20000,description:"Minuman kopi hitam murni dalam ukuran besar, diseduh dengan metode pour-over atau french press",image:"images/gedhe.png"},
  {id:11,name:"BLACK",variant:"Houseblend",category:"Menu Gedhe",price:20000,description:"Minuman kopi hitam murni dalam ukuran besar, dengan karakteristik biji Houseblend yang balanced dan nutty",image:"images/gedhe.png"},
  {id:12,name:"BLACK",variant:"Arabica",category:"Menu Gedhe",price:20000,description:"Minuman kopi hitam murni dalam ukuran besar, dengan karakteristik biji Arabica yang acidic, fruity, dan kompleks",image:"images/gedhe.png"},
  {id:13,name:"Banana Bread",variant:"Chocolate",category:"Snacks",price:12000,description:"Kue pisang lembut yang terbuat dari pisang asli, tepung, telur, dan mentega, dengan taburan cokelat chips",image:"images/snacks.png"},
  {id:14,name:"Banana Bread",variant:"Original",category:"Snacks",price:12000,description:"Kue pisang lembut yang terbuat dari pisang asli, tepung, telur, dan mentega, dengan rasa original",image:"images/snacks.png"},
  {id:15,name:"Basic Latte",variant:"Hot Arabica",category:"Coffee",price:23000,description:"Minuman klasik dengan 1 shot espresso dari biji kopi Arabica, susu steamed, dan lapisan microfoam yang tipis",image:"images/lattehot.png"},
  {id:16,name:"Basic Latte",variant:"Ice Houseblend",category:"Coffee",price:23000,description:"Minuman klasik dengan 1 shot espresso dari biji kopi Houseblend, susu dingin, dan es batu",image:"images/latteice.png"},
  {id:17,name:"Basic Latte",variant:"Hot Houseblend",category:"Coffee",price:23000,description:"Minuman klasik dengan 1 shot espresso dari biji kopi Houseblend, susu steamed, dan lapisan microfoam yang tipis",image:"images/lattehot.png"},
  {id:18,name:"Basic Latte",variant:"Ice Arabica",category:"Coffee",price:23000,description:"Minuman klasik dengan 1 shot espresso dari biji kopi Arabica, susu dingin, dan es batu",image:"images/latteice.png"},
  {id:19,name:"Berry Cake",variant:"-",category:"Other",price:24000,description:"Minuman manis asam segar terinspirasi dari kue lembut dengan lapisan krim dan campuran berry",image:"images/others.png"},
  {id:20,name:"Biru",variant:"-",category:"Coffee",price:24000,description:"Minuman menyegarkan berwarna biru cerah dengan perpaduan lemon dan sedikit soda",image:"images/latteice.png"},
  {id:21,name:"Biru (Gedhe)",variant:"-",category:"Menu Gedhe",price:30000,description:"Minuman ukuran besar menyegarkan berwarna biru cerah dengan perpaduan lemon dan sedikit soda",image:"images/gedhe.png"},
  {id:22,name:"Black Rice",variant:"Ice",category:"Other",price:23000,description:"Minuman manis gurih terinspirasi dari ketan hitam tradisional, disajikan dengan es",image:"images/others.png"},
  {id:23,name:"Black Rice",variant:"Hot",category:"Other",price:23000,description:"Minuman manis gurih terinspirasi dari ketan hitam tradisional, disajikan secara panas",image:"images/others.png"},
  {id:24,name:"Burnt Sugar",variant:"-",category:"Snacks",price:12000,description:"Kue donat klasik dengan lapisan gula yang dibakar di atasnya (creme brulee style)",image:"images/snacks.png"},
  {id:25,name:"Butterscotch",variant:"-",category:"Coffee",price:23000,description:"Minuman perpaduan espresso dan susu dengan sentuhan manis lembut dari sirup butterscotch",image:"images/latteice.png"},
  {id:26,name:"Butterscotch Latte (Gedhe)",variant:"-",category:"Menu Gedhe",price:30000,description:"Minuman ukuran besar dari perpaduan espresso dan susu dengan sentuhan manis lembut dari sirup butterscotch",image:"images/gedhe.png"},
  {id:27,name:"Candy Latte",variant:"-",category:"Coffee",price:23000,description:"Minuman latte dengan sentuhan manis seperti permen, memadukan espresso dan susu",image:"images/latteice.png"},
  {id:28,name:"Candy Latte (Gedhe)",variant:"-",category:"Menu Gedhe",price:30000,description:"Minuman ukuran besar dari latte dengan sentuhan manis seperti permen",image:"images/gedhe.png"},
  {id:29,name:"Cappuccino",variant:"Hot Houseblend",category:"Coffee",price:22000,description:"Minuman dengan komposisi 1:1:1 antara espresso dari biji kopi Houseblend, susu steamed, dan busa susu",image:"images/lattehot.png"},
  {id:30,name:"Cappuccino",variant:"Hot Arabica",category:"Coffee",price:22000,description:"Minuman dengan komposisi 1:1:1 antara espresso dari biji kopi Arabica, susu steamed, dan busa susu",image:"images/lattehot.png"},
  {id:31,name:"Cappuccino",variant:"Ice Houseblend",category:"Coffee",price:22000,description:"Minuman dengan komposisi 1:1:1 antara espresso dari biji kopi Houseblend, susu dingin dan busa susu",image:"images/latteice.png"},
  {id:32,name:"Cappuccino",variant:"Ice Arabica",category:"Coffee",price:22000,description:"Minuman dengan komposisi 1:1:1 antara espresso dari biji kopi Arabica, susu dingin dan busa susu",image:"images/latteice.png"},
  {id:33,name:"Chamomile",variant:"-",category:"Tea",price:20000,description:"Minuman panas teh herbal dari bunga chamomile kering yang memberikan efek menenangkan",image:"images/tea.png"},
  {id:34,name:"Chocolate",variant:"Hot",category:"Other",price:25000,description:"Minuman cokelat klasik dengan campuran kakao berkualitas dan susu steamed yang creamy",image:"images/others.png"},
  {id:35,name:"Chocolate",variant:"Ice",category:"Other",price:25000,description:"Minuman cokelat klasik dengan campuran kakao berkualitas, susu dingin dan es batu",image:"images/others.png"},
  {id:36,name:"Cold Brew",variant:"-",category:"Coffee",price:24000,description:"Kopi hasil seduhan dingin selama beberapa jam untuk rasa lebih halus, rendah asam, dan segar",image:"images/blackice.png"},
  {id:37,name:"Chocolate (Gedhe)",variant:"-",category:"Menu Gedhe",price:30000,description:"Minuman ukuran besar dari cokelat klasik dengan campuran kakao berkualitas, susu dingin dan es batu",image:"images/gedhe.png"},
  {id:38,name:"Creamy Klepon",variant:"-",category:"Other",price:24000,description:"Minuman manis terinspirasi dari rasa klepon khas Indonesia, memadukan pandan, gula merah, dan susu lembut",image:"images/others.png"},
  {id:39,name:"Donat Polos",variant:"-",category:"Snacks",price:10000,description:"Kue donat klasik tanpa topping yang memberikan tekstur empuk dan ringan",image:"images/snacks.png"},
  {id:40,name:"Espresso Arabica",variant:"On The Rock",category:"Coffee",price:12000,description:"Espresso dengan 100% biji Arabica yang dituangkan di atas es batu",image:"images/blackice.png"},
  {id:41,name:"Espresso Arabica",variant:"Basic Espresso",category:"Coffee",price:12000,description:"Espresso dengan 100% biji Arabica yang menghasilkan cita rasa lebih halus dan aromatik",image:"images/blackhot.png"},
  {id:42,name:"Espresso Houseblend",variant:"On The Rock",category:"Coffee",price:12000,description:"Espresso dengan pilihan biji Houseblend yang dituangkan di atas es batu",image:"images/blackice.png"},
  {id:43,name:"Espresso Houseblend",variant:"Basic Espresso",category:"Coffee",price:12000,description:"Espresso dengan pilihan biji Houseblend yang menghasilkan cita rasa nutty dan aromatik",image:"images/blackhot.png"},
  {id:44,name:"Extra Shot",variant:"Houseblend",category:"Add on",price:6000,description:"Tambahan 1 shot espresso dari pilihan biji Houseblend untuk cita rasa kopi yang lebih kuat",image:"images/addon.png"},
  {id:45,name:"Extra Shot",variant:"Arabica",category:"Add on",price:7000,description:"Tambahan 1 shot espresso dari pilihan biji 100% Arabica untuk cita rasa kopi yang lebih kuat",image:"images/addon.png"},
  {id:46,name:"Forbidden Berry",variant:"-",category:"Other",price:24000,description:"Minuman manis segar dengan perpaduan rahasia antara susu dingin dan berbagai buah beri",image:"images/others.png"},
  {id:47,name:"Friendly Coffee",variant:"Hot double shot",category:"Coffee",price:23000,description:"Minuman kopi susu dengan perpaduan double shot espresso, susu steamed dan gula aren",image:"images/lattehot.png"},
  {id:48,name:"Friendly Coffee",variant:"Ice double shot",category:"Coffee",price:23000,description:"Minuman kopi susu dengan perpaduan double shot espresso, susu dingin, es batu dan gula aren",image:"images/latteice.png"},
  {id:49,name:"Friendly Coffee",variant:"Hot",category:"Coffee",price:23000,description:"Minuman kopi susu dengan perpaduan single shot espresso, susu steamed dan gula aren",image:"images/lattehot.png"},
  {id:50,name:"Friendly Coffee",variant:"Ice",category:"Coffee",price:23000,description:"Minuman kopi susu dengan perpaduan single shot espresso, susu dingin, es batu dan gula aren",image:"images/latteice.png"},
  {id:51,name:"Friendly Coffee (Gedhe)",variant:"-",category:"Menu Gedhe",price:30000,description:"Minuman ukuran besar dari kopi susu dengan perpaduan double shot espresso, susu dingin, es batu dan gula aren",image:"images/gedhe.png"},
  {id:52,name:"Green Apple",variant:"-",category:"Tea",price:21000,description:"Minuman dingin bersoda yang menyegarkan dengan rasa apel hijau asam-manis",image:"images/tea.png"},
  {id:53,name:"Green Thai Tea",variant:"-",category:"Tea",price:21000,description:"Minuman teh hijau ala Thailand yang dipadukan dengan susu dingin, es batu, dan susu kental manis",image:"images/tea.png"},
  {id:54,name:"Green Thai Tea (Gedhe)",variant:"-",category:"Menu Gedhe",price:30000,description:"Minuman ukuran besar teh hijau ala Thailand yang dipadukan dengan susu dingin, es batu, dan susu kental manis",image:"images/gedhe.png"},
  {id:55,name:"Gula Gula",variant:"-",category:"Snacks",price:12000,description:"Kue donat klasik dengan topping gula putih yang memberikan tekstur lembut, empuk dan ringan",image:"images/snacks.png"},
  {id:56,name:"Happy Moca",variant:"Hot",category:"Coffee",price:30000,description:"Minuman campuran espresso, coklat bubuk, dan susu steamed yang memberi rasa creamy dan manis",image:"images/lattehot.png"},
  {id:57,name:"Happy Moca",variant:"Ice",category:"Coffee",price:30000,description:"Minuman campuran espresso, coklat bubuk, susu dingin dan es batu yang memberi rasa creamy dan manis",image:"images/latteice.png"},
  {id:58,name:"Hazelnut Latte",variant:"-",category:"Coffee",price:23000,description:"Minuman latte dari perpaduan lembut susu dingin, espresso, dan sirup hazelnut",image:"images/latteice.png"},
  {id:59,name:"Hazelnut Latte (Gedhe)",variant:"-",category:"Menu Gedhe",price:30000,description:"Minuman ukuran besar latte dari perpaduan lembut susu dingin, espresso, dan sirup hazelnut",image:"images/gedhe.png"},
  {id:60,name:"Jasmine",variant:"Ice",category:"Tea",price:21000,description:"Minuman dingin teh herbal dari bunga jasmine kering yang memberikan aroma lembut",image:"images/tea.png"},
  {id:61,name:"Jasmine",variant:"Hot",category:"Tea",price:21000,description:"Minuman panas teh herbal dari bunga jasmine kering yang memberikan aroma lembut",image:"images/tea.png"},
  {id:62,name:"Jus Semangka",variant:"-",category:"Other",price:22000,description:"Minuman jus segar dari potongan semangka asli tanpa tambahan pemanis buatan",image:"images/others.png"},
  {id:63,name:"Lemon Tea",variant:"Hot",category:"Tea",price:21000,description:"Minuman panas teh hitam dengan perasan buah lemon yang menyegarkan dan sedikit asam",image:"images/tea.png"},
  {id:64,name:"Lemon Tea",variant:"Ice",category:"Tea",price:21000,description:"Minuman dingin teh hitam dengan perasan buah lemon yang menyegarkan dan sedikit asam",image:"images/tea.png"},
  {id:65,name:"Lemons",variant:"-",category:"Other",price:20000,description:"Minuman dingin soda lemon segar dengan rasa masam ringan dan aroma citrus yang kuat",image:"images/others.png"},
  {id:66,name:"Matcha Espresso",variant:"-",category:"Coffee",price:25000,description:"Minuman perpaduan antara matcha, espresso, susu dingin dan es batu",image:"images/latteice.png"},
  {id:67,name:"Matcha Latte",variant:"Ice",category:"Other",price:24000,description:"Minuman latte perpaduan matcha Jepang dengan susu dingin, dan es batu yang menghasilkan rasa earthy dan creamy",image:"images/others.png"},
  {id:68,name:"Matcha Latte",variant:"Hot",category:"Other",price:24000,description:"Minuman latte perpaduan matcha Jepang dengan susu steamed yang menghasilkan rasa earthy dan creamy",image:"images/others.png"},
  {id:69,name:"Matcha Latte (Gedhe)",variant:"-",category:"Menu Gedhe",price:30000,description:"Minuman latte ukuran besar dari perpaduan matcha Jepang dengan susu dingin, dan es batu",image:"images/gedhe.png"},
  {id:70,name:"Matchapresso",variant:"-",category:"Coffee",price:25000,description:"Minuman perpaduan antara matcha, espresso, susu dingin dan es batu yang memberi keseimbangan rasa teh hijau dan pahit",image:"images/latteice.png"},
  {id:71,name:"Matchapresso (Gedhe)",variant:"-",category:"Menu Gedhe",price:30000,description:"Minuman ukuran besar dari perpaduan antara matcha, espresso, susu dingin dan es batu",image:"images/gedhe.png"},
  {id:72,name:"Moody",variant:"-",category:"Tea",price:23000,description:"Minuman dingin dari perpaduan teh hitam, jus citrus, dan es batu yang memberikan efek segar",image:"images/tea.png"},
  {id:73,name:"Nostaltea",variant:"-",category:"Tea",price:15000,description:"Minuman dingin teh hitam yang dipadukan dengan gula aren yang membangkitkan kenangan masa lalu",image:"images/tea.png"},
  {id:74,name:"Not Tiramisu Latte",variant:"-",category:"Coffee",price:24000,description:"Minuman latte perpaduan espresso, susu dingin, es batu dan sirup tiramisu tanpa alkohol",image:"images/latteice.png"},
  {id:75,name:"Not Tiramisu Latte (Gedhe)",variant:"-",category:"Menu Gedhe",price:30000,description:"Minuman latte ukuran besar dari perpaduan espresso, susu dingin, es batu dan sirup tiramisu tanpa alkohol",image:"images/gedhe.png"},
  {id:76,name:"Nutella Meses",variant:"-",category:"Snacks",price:12000,description:"Kue cokelat dengan campuran Nutella dan taburan meses yang menciptakan rasa manis khas",image:"images/snacks.png"},
  {id:77,name:"Red Apple",variant:"-",category:"Tea",price:21000,description:"Minuman dingin bersoda yang menyegarkan dengan rasa apel merah asam-manis",image:"images/tea.png"},
  {id:78,name:"Red Liquid",variant:"-",category:"Other",price:23000,description:"Minuman dingin perpaduan sirup strawbery dan delima, susu dingin, es batu dengan rasa asam segar",image:"images/others.png"},
  {id:79,name:"Shakencano",variant:"-",category:"Coffee",price:21000,description:"Minuman dingin perpaduan espresso dan gula aren yang dikocok dengan es batu, menghasilkan kopi dingin berbuih",image:"images/blackice.png"},
  {id:80,name:"Sitrus Cafe",variant:"-",category:"Coffee",price:24000,description:"Minuman dingin unik perpaduan antara espresso dan jus citrus, memberikan keseimbangan rasa segar asam dan pahit",image:"images/blackice.png"},
  {id:81,name:"Soft Tea",variant:"-",category:"Tea",price:18000,description:"Minuman dingin teh manis ringan dengan aroma lembut yang menyegarkan",image:"images/tea.png"},
  {id:82,name:"Summer",variant:"-",category:"Tea",price:23000,description:"Minuman dingin bersoda dengan perpaduan sirup buah tropis segar yang menghadirkan rasa manis",image:"images/tea.png"},
  {id:83,name:"Sunset",variant:"-",category:"Other",price:23000,description:"Minuman dingin dari perpaduan teh hitam, sirup strawberry, jus citrus, dan es batu yang menyegarkan",image:"images/others.png"},
  {id:84,name:"Susu Oat",variant:"-",category:"Add on",price:10000,description:"Tambahan susu alternatif berbahan dasar oat dengan rasa lembut dan sedikit gurih",image:"images/addon.png"},
  {id:85,name:"Thai Tea",variant:"-",category:"Tea",price:21000,description:"Minuman teh hitam ala Thailand yang dipadukan dengan susu dingin, es batu, dan susu kental manis",image:"images/tea.png"},
  {id:86,name:"Thai Tea (Gedhe)",variant:"-",category:"Menu Gedhe",price:30000,description:"Minuman ukuran besar dari teh hitam ala Thailand yang dipadukan dengan susu dingin, es batu, dan susu kental manis",image:"images/gedhe.png"},
  {id:87,name:"Upgrade Beans (Arabica)",variant:"-",category:"Add on",price:4000,description:"Tambahan pilihan untuk mengganti biji kopi Houseblend menjadi 100% Arabika",image:"images/addon.png"},
  {id:88,name:"Vanilla Latte",variant:"-",category:"Coffee",price:23000,description:"Minuman latte dari perpaduan lembut susu dingin, espresso, dan sirup vanilla",image:"images/latteice.png"},
  {id:89,name:"Vanilla Latte (Gedhe)",variant:"-",category:"Menu Gedhe",price:30000,description:"Minuman ukuran besar latte dari perpaduan lembut susu dingin, espresso, dan sirup vanilla",image:"images/gedhe.png"},
  {id:90,name:"WHITE",variant:"-",category:"Menu Gedhe",price:30000,description:"Minuman dingin kopi susu ringan dengan perpaduan espresso lembut dan susu dingin creamy khas signature kafe",image:"images/gedhe.png"},
  {id:91,name:"WHITE",variant:"Houseblend",category:"Menu Gedhe",price:30000,description:"Minuman dingin kopi susu ringan dengan perpaduan espresso dari biji kopi Houseblend dan susu dingin creamy",image:"images/gedhe.png"},
  {id:92,name:"WHITE",variant:"Arabica",category:"Menu Gedhe",price:30000,description:"Minuman dingin kopi susu ringan dengan perpaduan espresso dari biji kopi 100% Arabica dan susu dingin creamy",image:"images/gedhe.png"},
  {id:93,name:"Croffle",variant:"-",category:"Snacks",price:28000,description:"Kue croissant dipanggang di waffle iron, renyah di luar, lembut di dalam",image:"images/snacks.png"},
  {id:94,name:"Creamy Chocolate Cake",variant:"-",category:"Other",price:30000,description:"Kue cokelat lembut bertekstur krim (mousse-style) dengan lapisan ganache yang manis dan lembut",image:"images/others.png"},
  {id:95,name:"Waffle",variant:"-",category:"Snacks",price:25000,description:"Kue waffle panas, tekstur renyah di luar dan empuk di dalam",image:"images/snacks.png"},
  {id:96,name:"Pisang Coklat",variant:"-",category:"Snacks",price:22000,description:"Kue pisang yang dilapisi kulit renyah yang goreng dengan isi topping cokelat (1 porsi isi 2)",image:"images/snacks.png"},
];

const CATEGORIES = ["Semua", "Coffee", "Tea", "Other", "Snacks", "Menu Gedhe", "Add on"];

function getVariants() {
  const varSet = new Set();
  PRODUCTS.forEach(p => { if (p.variant && p.variant !== "-") varSet.add(p.variant); });
  return ["Semua", ...Array.from(varSet).sort()];
}

function formatPrice(price) {
  if (price === 0) return "Gratis";
  return "Rp " + price.toLocaleString("id-ID");
}
